---
- name: Provisioning Software
  hosts: localhost
  gather_facts: no
  become: true
  vars:
    tars:
      helm:
        url: https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
        checksum: sha256:cdd7ad304e2615c583dde0ffb0cb38fc1336cd7ce8ff3b5f237434dcadb28c98
        download_path: /tmp/helm.tar.gz
        unpacked_path: /tmp/linux-amd64/helm
        execute_path: /usr/bin/helm
        file_mode: 0111
    rpms:
      git:
        package: rh-git218
        rpm: https://access.cdn.redhat.com/content/origin/rpms/git/2.18.2/1.el8_1/fd431d51/git-2.18.2-1.el8_1.x86_64.rpm 

  tasks:
  - name: Add repositories
    yum_repository:
      name: "{{ item }}"
      baseurl: "{{ item.value.rpm }}"
    with_dict: "{{ rpms }}"

  - name: Install RPM packages
    yum:
      name: {{ item.value.package }}
      state: present
    with_dict: {{ rpms }}
    
  - name: Downloading software tarballs
    get_url:
      url: "{{ item.value.url }}"
      dest: "{{ item.value.download_path }}"
      checksum: "{{ item.value.checksum }}"
    with_dict: "{{ tars }}"

  - name: Unpacking tarballs
    unarchive:
      src: "{{ item.value.download_path }}"
      dest: /tmp
    with_dict: "{{ tars }}"

  - name: Moving binaries to path
    copy:
      src: "{{ item.value.unpacked_path }}"
      dest: "{{ item.value.execute_path }}"
      mode: "{{ item.value.file_mode }}"
    with_dict: "{{ tars }}"

